export const USER_LOGIN_SUCCESS = "LATEST_MOVIES_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const FETCH_CARS_ERROR = "FETCH_CARS_ERROR";
export const FETCH_CARS_SUCCESS = "FETCH_CARS_SUCCESS";
